---
name: Deploy Backend Core Django Project on AWS EC2
on:
  push:
    branches:
      - main
    paths:
      - Backend/**
jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          TARGET: ${{ secrets.DJANGO_PROJECT_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            source venv/bin/activate
            cd ${{ secrets.DJANGO_PROJECT_DIR }}
            git pull origin main
            pip install -r requirements.txt
            python manage.py makemigrations
            python manage.py migrate
            python manage.py collectstatic --noinput
